<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <RestoreLockedMode>true</RestoreLockedMode>
    <RestorePackagesPath Condition="'$(RestorePackagesPath)'==''">$(MSBuildThisFileDirectory)restore\packages</RestorePackagesPath>
    <RestoreNoHttpCache>true</RestoreNoHttpCache>
    <RestoreFallbackFolders></RestoreFallbackFolders>
    <RestoreAdditionalProjectFallbackFolders></RestoreAdditionalProjectFallbackFolders>
    <RestoreAdditionalProjectFallbackFoldersExcludes></RestoreAdditionalProjectFallbackFoldersExcludes>
    <DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
  </PropertyGroup>
</Project>
